### ISSUE TITLE
Add Support for Dart >= 2.0.0

### ISSUE THREAD

**Issue by Robarelli** [Workiva/state_machine#45]
> The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.
> 
> Because {appName} depends on state_machine >=2.0.0 which requires SDK version >=1.9.0 <2.0.0, version solving failed.
> pub get failed (1)

**Comment by bradyt** [comment]
Should this be closed?

**Comment by evanweible-wf** [comment]
Yes it should, thanks @bradyt!
